### ISSUE TITLE
Light sleep while waiting for GPS fix

### ISSUE THREAD

**Issue by stkdiretto** [stadtulm/feuchtraumabzweigdose-testing#1]
Currently, the tracker waits actively for the GPS to acquire a fix. This usually takes between 20 to 120 seconds, in which the µC idles at full power. There should be quite some power saving potential in putting the ESP in light sleep mode and either periodically poll for a valid fix, or only wake up by the PPS signal as an external wakeup source.

**Comment by jayAitch256** [comment]
Solved by https://github.com/stadtulm/feuchtraumabzweigdose-testing/commit/4ecdd41d867827f968f57998b4e1adab192ae68e

I chose the polling option since connecting the PPS pin to the PCB does not seem to be intended.
