### ISSUE TITLE
Fallback to wifi tracker mode if battery is too low

### ISSUE THREAD

**Issue by stkdiretto** [stadtulm/feuchtraumabzweigdose-testing#4]
One option to squeeze a bit more lifespan out of the tracker is to measure battery voltage and then decide whether to even power up the GPS or rely solely on collecting Wifi SSIDs and submitting them.

**Comment by jayAitch256** [comment]
Solved by https://github.com/stadtulm/feuchtraumabzweigdose-testing/commit/8422bccf82261fcc5714cfe97c5ac760e79e2c04 and https://github.com/stadtulm/feuchtraumabzweigdose-testing/commit/16a4a2337eddfe4948121b5ebf5dd4aedae15901
